### ISSUE TITLE
Why use Jar file?

### ISSUE THREAD

**Issue by Cortlandd** [ShaofengZou/Android-Style-Transfer#1]
Why did you use the tensorflow jar file as opposed to adding tensorflow-android to gradle? 

https://mvnrepository.com/artifact/org.tensorflow/tensorflow-android/1.13.1

**Comment by ShaofengZou** [comment]
It may work either. I didn't try it because i directly work based on other's project. 
If it works, welcome to make a pull requests ^_^

**Comment by Cortlandd** [comment]
@ShaofengZou 

Thanks!

Another question, I'm working on a project and I followed your algorithm for handling the output image results. It works perfect but the quality I expect is off. Can I send you an email to show you the issue I've run into?

**Comment by ShaofengZou** [comment]
OK, fine.

**Comment by Cortlandd** [comment]
Sent you an email.
