### ISSUE TITLE
Model Error while running the app

### ISSUE THREAD

**Issue by maldivien** [ShaofengZou/Android-Style-Transfer#2]
using the model that you have provided in the transfer directory, i got this error.

Caused by: java.lang.IllegalArgumentException: No Operation named [input] in the Graph
                      at org.tensorflow.Session$Runner.operationByName(Session.java:356)
                      at org.tensorflow.Session$Runner.feed(Session.java:142)
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.addFeed(TensorFlowInferenceInterface.java:567)
                      at org.tensorflow.contrib.android.TensorFlowInferenceInterface.feed(TensorFlowInferenceInterface.java:308)
                      at com.shaofengzou.styletransfer.MainActivity.stylizeImage(MainActivity.java:376)
                      at com.shaofengzou.styletransfer.MainActivity.access$1400(MainActivity.java:46)
                      at com.shaofengzou.styletransfer.MainActivity$StylizeTask.doInBackground(MainActivity.java:331)
                      at com.shaofengzou.styletransfer.MainActivity$StylizeTask.doInBackground(MainActivity.java:307)

**Comment by maldivien** [comment]
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
W/System: A resource failed to call close. 
W/System: A resource failed to call close. 
I/TensorFlowInferenceInterface: Model load took 37ms, TensorFlow version: 1.4.0
I/TensorFlowInferenceInterface: Successfully loaded model from 'file:///android_asset/500.pb'
E/StyleTransfer: Stage 1, width:512
                 Stage 1, height:512
                 Start style transfer
I/TensorFlowInferenceInterface: Checking to see if TensorFlow native methods are already loaded
I/TensorFlowInferenceInterface: TensorFlow native methods already loaded
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
I/TensorFlowInferenceInterface: Model load took 24ms, TensorFlow version: 1.4.0
I/TensorFlowInferenceInterface: Successfully loaded model from 'file:///android_asset/500.pb'

**Comment by ShaofengZou** [comment]
May be you should run the step2 and step3 to generate the pb model.
You can check the input and output node by using "test_pb_file.py"

**Comment by maldivien** [comment]
> May be you should run the step2 and step3 to generate the pb model.
> You can check the input and output node by using "test_pb_file.py"

Will check it. So the model inside the part one wont work?

can u explain the following? maybe the model im using is supposed to be greater than 8 in the list. 
                if (style_pos < 8) {
                    INPUT_NODE = "X_inputs";
                    OUTPUT_NODE = "output";
                    width = 512;
                    height = 512;
                } else if (style_pos == 4) {
                    INPUT_NODE = "input";
                    OUTPUT_NODE = "output";
                    width = 480;
                    height = 640;
                } else {
                    INPUT_NODE = "input";
                    OUTPUT_NODE = "output_new";
                    width = 512;
                    height = 512;
                }

**Comment by maldivien** [comment]
I have successfully tested the model with "test_pb_file.py" and now i have got a new error.

                   `                   Caused by: java.lang.IllegalArgumentException: input must be 4-dimensional[512,512,3]
                  	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_X_inputs_0_0, Variable/read)]]
                      at org.tensorflow.Session.run(Native Method)`

**Comment by ShaofengZou** [comment]
As I mentioned in readme, l cheat some models trained by others and merge them in this project. So the models may have different input node name and output node name. That's why you should use "test_pb_file.py" to confirm the node name and change corresponding code in the android project.

Remember to match the input node name , output node name, input dimensions and ouput dimensions both in python project and android project.  That's the key point.

**Comment by surbanczyk** [comment]
Could you upload the model to Google drive ? I can't register to your cloud storage from my country

**Comment by ShaofengZou** [comment]
All right, I have upload the model to [Google drive](https://drive.google.com/open?id=1tTj7I8WnYQYNhFwqgX8av6Gr2rAJ17hq).
